### ISSUE TITLE
GUI should update when subscriptions are added/canceled

### ISSUE THREAD

**Issue by lukeprofits** [lukeprofits/Monero_Subscriptions_Wallet#1]
I haven't been able to figure out an easy way to get the GUI to visually update when subscriptions are added/canceled. This shouldn't be a hard thing to fix, I just haven't had time to get into it. As a temporary workaround, we are showing a pop-up that says that the wallet will now close and to restart it. If we can fix this, it will be a lot less annoying for users.

**Comment by PySimpleGUI** [comment]
Don't know if you're tried adding `window.refresh()` to your code.  Anytime something in the window changes and you want to see the change immediately/before window.read is called, you'll need to refresh.  

If you're extending the layout by adding elements to a scrollable column, then contents_changed needs to be called.

There are a lot of situations that can cause something to not show up as expected.

Your best bet is going to be to ask your question on the PySimpleGUI GitHub
https://Issues.PySimpleGUI.org

If you can state what you're doing to the GUI specifically then we should be able to give ya a hand.

**Comment by PySimpleGUI** [comment]
I'll assume you've not found anything about extending layouts.... adding and deleting elements after the window is open.

There are several demo programs that show how to do this.  Look in the docs and demos for `extend_layout`.   You can add elements to any Container Element.  You can "delete" elements by making them not visible.  It's not a true delete and allows you to bring them back later if you wish, but does visibly remove them from the GUI.

Here's one of the demo programs using this method.  It's what I use in my utilities when I need to add or delete entries at runtime.

![explorer_abMsdroqTO](https://github.com/lukeprofits/Monero_Subscriptions_Wallet/assets/46163555/65ca2e50-306a-449b-8f2f-9845f2a22876)
