### ISSUE TITLE
Would be cool to have an option to sweep all funds out of the wallet and transfer to another wallet.

### ISSUE THREAD

**Issue by lukeprofits** [lukeprofits/Monero_Subscriptions_Wallet#12]
Would be cool to have an option to sweep all funds out of the wallet and transfer to another wallet. Would have to be done in a way that doesn't make the GUI look ugly. 

Idea: Users have to paste the wallet address, NOT enter an amount, hold the button down and if they hold it for more than 3 seconds, they get a pop-up that says "Transfer Entire Balance? Yes/No" (is that possible in PySimpleGUI or does it just register click events?) .

**Comment by GergelyGombai** [comment]
> Would be cool to have an option to sweep all funds out of the wallet and transfer to another wallet. Would have to be done in a way that doesn't make the GUI look ugly.
> 
> Idea: Users have to paste the wallet address, NOT enter an amount, hold the button down and if they hold it for more than 3 seconds, they get a pop-up that says "Transfer Entire Balance? Yes/No" (is that possible in PySimpleGUI or does it just register click events?) .

Will check, would be cool.

**Comment by GergelyGombai** [comment]
just a button with transefer entire balance and a confirm popup which you have to type CONFIRM to would be easier.

**Comment by lukeprofits** [comment]
I want the UI to stay really clean looking. Maybe we could set it so that if someone hits send after entering a wallet but NOT entering an amount, it makes a popup that says "Do you want to send ALL funds to this wallet address?", and then they have to click yes, and and then an "Are you sure?" popup. 

Yes, Yes would be less annoying than typing "confirm", but still secure enough that you won't do it by accident. Also probably a bit easier to put together.

**Comment by GergelyGombai** [comment]
Sure

**Comment by GergelyGombai** [comment]
done
